name: Check security alerts

on:
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          github-token: ${{ secrets.ACTIVE_TOKEN }}
          result-encoding: string
          script: |
            if (!'${{secrets.SECURITY_ISSUE_REPO}}')
               return;

            let result = '';
            const { owner, repo } = context.repo;
            const state           = 'open';

            const labels = {
              dependabot: 'dependabot',
              codeq:      'codeql',
              security:   'security notification',
            };

            const dependabotAlerts      = await getDependabotAlerts();
            const codeqlAlerts          = await getCodeqlAlerts();
            const {data: existedIssues} = await github.rest.issues.listForRepo({ 
              owner, 
              repo:   '${{ secrets.SECURITY_ISSUE_REPO }}', 
              labels: [labels.security], 
              state 
            });

            const alertDictionary = existedIssues.reduce((res, issue) => {
              const [,alertUrl, alertNumber] = issue.body.match(/Link:\s*(https.*?(\d+)$)/);

              result += alertUrl + ',';

              if (!alertUrl)
                return res;

              res[alertUrl] = {
                issue,
                number: alertNumber,
                isDependabot: alertUrl.includes('dependabot'),
              };

              return res;
            }, {})

            result += Object.keys(alertDictionary).length + ',';
            for (const key in alertDictionary) {
              var alert = alertDictionary[key];

              result += await isDependabotAlertOpen(alert.number) + ','
              console.log(`Is opened: ${await isDependabotAlertOpen(alert.number)}`);
              result += alert.issue.number + ','
              console.log(`Alert number: ${alert.issue.number}`);

              if (alert.isDependabot) {
                const isAlertOpened = await isDependabotAlertOpen(alert.number);

                if (!isAlertOpened)
                  await closeIssue(alert.issue.number)
              }
            }

            dependabotAlerts.forEach(alert => {
              if (!needCreateIssue(alert))
                return;

              createIssue({ owner, 
                repo:        '${{ secrets.SECURITY_ISSUE_REPO }}', 
                labels:      [labels.dependabot, labels.security, alert.dependency.scope], 
                originRepo:  repo,
                summary:     alert.security_advisory.summary, 
                description: alert.security_advisory.description, 
                link:        alert.html_url, 
                package:     alert.dependency.package.name
              })
            });

            codeqlAlerts.forEach(alert => {
              if (!needCreateIssue(alert))
                return;

              createIssue({ owner, 
                repo:        '${{ secrets.SECURITY_ISSUE_REPO }}', 
                labels:      [labels.codeql, labels.security], 
                originRepo:  repo,
                summary:     alert.rule.description, 
                description: alert.most_recent_instance.message.text, 
                link:        alert.html_url, 
              })
            });

            return result + "Hello!";

            async function getDependabotAlerts () {
              const dependabotListAlertsUrl  = `https://api.github.com/repos/${ owner }/${ repo }/dependabot/alerts?state=${ state }`;
              const dependabotRequestOptions = {
                headers: { 'Authorization': 'Bearer ${{ secrets.ACTIVE_TOKEN }}' }
              }

              const response = await fetch(dependabotListAlertsUrl, dependabotRequestOptions);
              const data     = await response.json();

              // If data isn't arry somethig goes wrong
              if (Array.isArray(data))
                return data;

              return [];
            }

            async function getCodeqlAlerts () {
              // When CodeQL is turned of it throws error
              try {
                const { data }  = await github.rest.codeScanning.listAlertsForRepo({ owner, repo, state });

                return data;
              } catch (_) {
                return [];
              }
            }

            async function isDependabotAlertOpen (alertNumber) {
              const alert = await getDependabotAlertInfo(alertNumber);

              return alert?.state == 'open';
            }

            async function getDependabotAlertInfo (alertNumber) {
              const dependabotListAlertsUrl  = `https://api.github.com/repos/${ owner }/${ repo }/dependabot/alerts/${ alertNumber }`;
              const dependabotRequestOptions = {
                headers: { 'Authorization': 'Bearer ${{ secrets.ACTIVE_TOKEN }}' }
              }

              const response = await fetch(dependabotListAlertsUrl, dependabotRequestOptions);
              const data     = await response.json();

              if (data.state)
                return data;

              return null;
            }

            function needCreateIssue (alert) {
              return !alertDictionary[alert.html_url];
            }

            async function createIssue ({owner, repo, labels, originRepo, summary, description, link, package = ''}) {
              const title = `[${originRepo}] ${summary}`;
              const body  = ''
                + `#### Repository: \`${ originRepo }\`\n`
                + (!!package ? `#### Package: \`${ package }\`\n` : '')
                + `#### Description:\n`
                + `${ description }\n`
                + `#### Link: ${ link }`

              return github.rest.issues.create({ owner, repo, title, body, labels });
            }

            async function closeIssue (number) {
              console.log('Close issue');

              const closeResult = await github.rest.issues.update({ owner, repo, issue_number: number, state: 'closed' });

              result += closeResult + ', ';

              return closeResult;
            }
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"